Export and import all databases, not only `homeassistant`

diff --git a/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core-post/run b/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core-post/run
--- a/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core-post/run
+++ b/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core-post/run
@@ -55,51 +55,79 @@ for database in $(bashio::config "databases"); do
     mysql -e "CREATE DATABASE ${database};" 2> /dev/null || true
 done
 
+# Cleanup failed export - old version
+if bashio::fs.file_exists "${OLD_MARIADB_DUMP_FINISHED}"; then
+    if bashio::fs.file_exists "${OLD_MARIADB_DUMP/TYPE/schema}.tmp"; then
+        rm -f ${OLD_MARIADB_DUMP/TYPE/schema}
+        mv ${OLD_MARIADB_DUMP/TYPE/schema}.tmp ${OLD_MARIADB_DUMP/TYPE/schema}
+    fi
+    if bashio::fs.file_exists "${OLD_MARIADB_DUMP/TYPE/data1}.tmp"; then
+        rm -f ${OLD_MARIADB_DUMP/TYPE/data1}
+        mv ${OLD_MARIADB_DUMP/TYPE/data1}.tmp ${OLD_MARIADB_DUMP/TYPE/data1}
+    fi
+    if bashio::fs.file_exists "${OLD_MARIADB_DUMP/TYPE/data2}.tmp"; then
+        rm -f ${OLD_MARIADB_DUMP/TYPE/data2}
+        mv ${OLD_MARIADB_DUMP/TYPE/data2}.tmp ${OLD_MARIADB_DUMP/TYPE/data2}
+    fi
+    rm ${OLD_MARIADB_DUMP_FINISHED}
+else
+    rm -f ${OLD_MARIADB_DUMP/TYPE/schema}.tmp
+    rm -f ${OLD_MARIADB_DUMP/TYPE/data1}.tmp
+    rm -f ${OLD_MARIADB_DUMP/TYPE/data2}.tmp
+fi
+
 # Cleanup failed export
 if bashio::fs.file_exists "${MARIADB_DUMP_FINISHED}"; then
-    if bashio::fs.file_exists "${MARIADB_DUMP/TYPE/schema}.tmp"; then
-        rm -f ${MARIADB_DUMP/TYPE/schema}
-        mv ${MARIADB_DUMP/TYPE/schema}.tmp ${MARIADB_DUMP/TYPE/schema}
-    fi
-    if bashio::fs.file_exists "${MARIADB_DUMP/TYPE/data1}.tmp"; then
-        rm -f ${MARIADB_DUMP/TYPE/data1}
-        mv ${MARIADB_DUMP/TYPE/data1}.tmp ${MARIADB_DUMP/TYPE/data1}
-    fi
-    if bashio::fs.file_exists "${MARIADB_DUMP/TYPE/data2}.tmp"; then
-        rm -f ${MARIADB_DUMP/TYPE/data2}
-        mv ${MARIADB_DUMP/TYPE/data2}.tmp ${MARIADB_DUMP/TYPE/data2}
+    if bashio::fs.file_exists "${MARIADB_DUMP}.tmp"; then
+        rm -f ${MARIADB_DUMP}
+        mv ${MARIADB_DUMP}.tmp ${MARIADB_DUMP}
     fi
     rm ${MARIADB_DUMP_FINISHED}
 else
-    rm -f ${MARIADB_DUMP/TYPE/schema}.tmp
-    rm -f ${MARIADB_DUMP/TYPE/data1}.tmp
-    rm -f ${MARIADB_DUMP/TYPE/data2}.tmp
+    rm -f ${MARIADB_DUMP}.tmp
 fi
 
 # Import database structure and content... (no connection is allowed until it is finished)
 if bashio::config.exists "retention.enabled" && bashio::fs.directory_exists "${MARIADB_DATA}/homeassistant"; then
     if bashio::config.true "retention.enabled"; then
-        EXPORT_IMPORT_DATABASE_CONTENT=true
-        printf "${EXPORT_IMPORT_DATABASE_CONTENT}" > /var/run/s6/container_environment/EXPORT_IMPORT_DATABASE_CONTENT
-        if ! bashio::fs.file_exists "${MARIADB_DUMP/TYPE/schema}"; then
+        EXPORT_IMPORT_DATABASES_CONTENT=true
+        printf "${EXPORT_IMPORT_DATABASES_CONTENT}" > /var/run/s6/container_environment/EXPORT_IMPORT_DATABASES_CONTENT
+        if ! bashio::fs.file_exists "${OLD_MARIADB_DUMP/TYPE/schema}" \
+            && ! bashio::fs.file_exists "${MARIADB_DUMP}"
+        then
             bashio::log.warning "Importing last known database content skipped, no dump file found"
         else
-            bashio::log.info "Last known database content time stamp is $(stat ${MARIADB_DUMP/TYPE/schema} -c %y)"
-            bashio::log.info "Importing database structure and content... (no connection is allowed until it is finished)"
-            gzip -d ${MARIADB_DUMP/TYPE/schema} -c \
-                | mysql homeassistant
-            gzip -d ${MARIADB_DUMP/TYPE/data1} -c \
-                | mysql homeassistant
-            gzip -d ${MARIADB_DUMP/TYPE/data2} -c \
-                | mysql homeassistant
+            if bashio::fs.file_exists "${OLD_MARIADB_DUMP/TYPE/schema}"; then
+                # old version
+                bashio::log.info "Last known database content time stamp is $(stat ${OLD_MARIADB_DUMP/TYPE/schema} -c %y)"
+                bashio::log.info "Importing database structure and content... (no connection is allowed until it is finished)"
+                gzip -d ${OLD_MARIADB_DUMP/TYPE/schema} -c \
+                    | mysql homeassistant
+                gzip -d ${OLD_MARIADB_DUMP/TYPE/data1} -c \
+                    | mysql homeassistant
+                gzip -d ${OLD_MARIADB_DUMP/TYPE/data2} -c \
+                    | mysql homeassistant
+            else
+                # new version
+                bashio::log.info "Last known database content time stamp is $(stat ${MARIADB_DUMP} -c %y)"
+                bashio::log.info "Importing database structure and content... (no connection is allowed until it is finished)"
+                gzip -d ${MARIADB_DUMP} -c \
+                    | mysql
+            fi
             # Bugfix for v2.5.2.4 unnecessary schema version insertion
             mysql homeassistant -e "DELETE FROM schema_changes WHERE change_id=1 AND schema_version=35;"
         fi
     else
-        if bashio::fs.file_exists "${MARIADB_DUMP/TYPE/schema}"; then
-            rm -f ${MARIADB_DUMP/TYPE/schema}
-            rm -f ${MARIADB_DUMP/TYPE/data1}
-            rm -f ${MARIADB_DUMP/TYPE/data2}
+        # old version
+        if bashio::fs.file_exists "${OLD_MARIADB_DUMP/TYPE/schema}"; then
+            rm -f ${OLD_MARIADB_DUMP/TYPE/schema}
+            rm -f ${OLD_MARIADB_DUMP/TYPE/data1}
+            rm -f ${OLD_MARIADB_DUMP/TYPE/data2}
+            bashio::log.info "Data retention is explicitly turned off, unused exported database content is removed"
+        fi
+        # new version
+        if bashio::fs.file_exists "${MARIADB_DUMP}"; then
+            rm -f ${MARIADB_DUMP}
             bashio::log.info "Data retention is explicitly turned off, unused exported database content is removed"
         fi
     fi
