avoid infinite loop on start

diff --git a/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core/run b/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core/run
--- a/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core/run
+++ b/mariadb/rootfs/etc/s6-overlay/s6-rc.d/mariadb-core/run
@@ -10,9 +10,14 @@ mysqld --datadir="${MARIADB_DATA}" --user=root < /dev/null &
 MARIADB_PID=$!
 
 # Wait until DB is running
-while ! mysql -e "" 2> /dev/null; do
+while [[ test -d /proc/"${MARIADB_PID}"/ && ! mysql -e "" 2> /dev/null ]]; do
     sleep 1
 done
+if [[ ! test -d /proc/"${MARIADB_PID}"/ ]]; then
+    bashio::log.info "MariaDB failed to start"
+    exit 1
+fi
+
 bashio::log.info "MariaDB started"
 
 # Notify s6 about successful service start
